# Generated by Django 5.0.4 on 2024-04-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='grocery_list',
        ),
        migrations.DeleteModel(
            name='GroceryList',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
